name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.22.0"
      - run: deno bundle ./client/client.js ./static/client.bundle.js
      - uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.PROJECT_NAME }}
          entrypoint: server.jsx